### ISSUE TITLE
Unable to use RestSH on MS Windows Machine!

### ISSUE THREAD

**Issue by dsfb** [jespino/restsh#5]
Hi,

I was trying to use this app, RestSH, on a MS Windows Machine, but it failed...

I installed this app with Python 3.5.2, then I tried the following commands in the Command Prompt:
"restSH",
"restsh" and
"RestSH"
, but none of them worked like I expected...

Please, help me to understand why it occurred with RestSH!

Should this app to be running on a Linux Machine?

Best Regards,
Daniel Bruno.

**Comment by jespino** [comment]
Hi Daniel, this project is a bit unmaintained. Anyway is developed under linux, and is thinked to be used in linux, so I'm not sure if this works on Windows, and how to make it work on Windows. I'm not use windows at all, so, I'm sorry, I can't help you :disappointed:

**Comment by dsfb** [comment]
Ok!
Thanks for you, jespino!
By the way, I am going to close this issue!

Best Regards,
dsfb.
